# Written by WATO
# encoding: utf-8

SITES = \
{'MASTER': {'alias': u'MASTER NODE',
            'disabled': False,
            'insecure': False,
            'multisiteurl': '',
            'persist': False,
            'repl_priority': 0,
            'timeout': 10,
            'url_prefix': '/master/'},
 'OPTIONSHOUSE': {'alias': u'OPTIONSHOUSE Node',
                  'disabled': False,
                  'insecure': False,
                  'multisiteurl': 'http://oslchi6pmon1/prod/check_mk/',
                  'persist': False,
                  'repl_priority': 0,
                  'socket': 'tcp:oslchi6pmon1:6557',
                  'timeout': 10,
                  'url_prefix': '/prod/'},
 'OPTIONSHOUSE_snmp': {'alias': u'OPTIONSHOUSE_snmp NODE',
                       'disabled': False,
                       'insecure': False,
                       'multisiteurl': 'http://oslchi6pmon1/hardware/check_mk/',
                       'persist': False,
                       'repl_priority': 0,
                       'socket': 'tcp:oslchi6pmon1:6558',
                       'timeout': 10,
                       'url_prefix': '/hardware/'},
 'SAVVIS': {'alias': u'SAVVIS NODE',
            'disabled': False,
            'insecure': False,
            'multisiteurl': 'http://sslchi5pmon1/savvis/check_mk/',
            'persist': False,
            'replication': 'slave',
            'secret': 'VPXRVMBIDU;7AU;<WD4=4@7Y7E0;ZS34',
            'socket': 'tcp:sslchi5pmon1:6557',
            'timeout': 10,
            'url_prefix': '/savvis/'},
 'SAVVIS_dev': {'alias': u'SAVVIS_dev NODE',
                'disabled': False,
                'insecure': False,
                'multisiteurl': 'http://sslchi5pmon1/savvis_dev/check_mk/',
                'persist': False,
                'replication': 'slave',
                'secret': 'DK:ANFF6O>K@OLY1<9ACT:UEEX7S>K1Q',
                'socket': 'tcp:sslchi5pmon1:6560',
                'timeout': 10,
                'url_prefix': '/savvis_dev/'},
 'SAVVIS_snmp': {'alias': u'SAVVIS_snmp NODE',
                 'disabled': False,
                 'insecure': False,
                 'multisiteurl': 'http://sslchi5pmon1/savvis_snmp/check_mk/',
                 'persist': False,
                 'repl_priority': 0,
                 'socket': 'tcp:sslchi5pmon1:6558',
                 'timeout': 20,
                 'url_prefix': '/savvis_snmp/'},
 'SAVVIS_stage': {'alias': u'SAVVIS_stage NODE',
                  'disabled': False,
                  'insecure': False,
                  'multisiteurl': 'http://sslchi5pmon1/savvis_stage/check_mk/',
                  'persist': False,
                  'replication': 'slave',
                  'secret': 'YQ=VWXAC4JMNHZ>XCF710TSCLZGL38IN',
                  'socket': 'tcp:sslchi5pmon1:6559',
                  'timeout': 10,
                  'url_prefix': '/savvis_stage/'},
 'STARGATE': {'alias': u'STARGATE NODE',
              'disabled': False,
              'insecure': False,
              'multisiteurl': 'http://sslchi6pmon2/stargate/check_mk/',
              'persist': False,
              'replication': 'slave',
              'secret': 'R6TTK:?Y8C9G:BIWRCSRIF?;3@1=?IRZ',
              'socket': 'tcp:sslchi6pmon2:6557',
              'timeout': 10,
              'url_prefix': '/stargate/'},
 'STARGATE_dev': {'alias': u'STARGATE_dev NODE',
                  'disabled': False,
                  'insecure': False,
                  'multisiteurl': 'http://sslchi6pmon2/stargate_dev/check_mk/',
                  'persist': False,
                  'replication': 'slave',
                  'secret': 'GEUQ>YK27M=T24;;93AUSSW4?9X7>L2D',
                  'socket': 'tcp:sslchi6pmon2:6559',
                  'timeout': 10,
                  'url_prefix': '/stargate_dev/'},
 'STARGATE_snmp': {'alias': u'STARGATE_snmp NODE',
                   'disabled': False,
                   'insecure': False,
                   'multisiteurl': 'http://sslchi6pmon2/stargate_snmp/check_mk/',
                   'persist': False,
                   'repl_priority': 0,
                   'socket': 'tcp:sslchi6pmon2:6558',
                   'timeout': 10,
                   'url_prefix': '/stargate_snmp/'},
 'STARGATE_stage': {'alias': u'STARGATE_stage NODE',
                    'disabled': False,
                    'insecure': False,
                    'multisiteurl': 'http://sslchi6pmon2/stargate_stage/check_mk/',
                    'persist': False,
                    'replication': 'slave',
                    'secret': 'A3?R;2IH5W:8A@VF0:65G9HHGFFNX5<J',
                    'socket': 'tcp:sslchi6pmon2:6560',
                    'timeout': 10,
                    'url_prefix': '/stargate_dev/'}}
